theme: jekyll-theme-minimal
logo: /images/headshot.png
title: Ben Nguyen
description: >
 Graduated Master of Analytics at Massey University. <br>
 <br>Seeking a data analyst or data engineer role. <br><br>

 <a href="https://www.linkedin.com/in/bennguyen1201/">View My LinkedIn Profile</a> 
show_downloads: true
